<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="A5364L" failures="1" tests="4" name="lightstorm.polarin.testCases.CreateVirtualRouterTestCase" time="19.109" errors="0" timestamp="2023-07-03T17:59:52 IST" skipped="0">
  <testcase classname="lightstorm.polarin.testCases.CreateVirtualRouterTestCase" name="closebrowser" time="0.001">
    <failure message="The following asserts failed:
	expected [] but found [421199842]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [] but found [421199842]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at lightstorm.polarin.utility.SoftAssertUtil.assertAll(SoftAssertUtil.java:24)
at lightstorm.polarin.testCases.CreateVirtualRouterTestCase.closebrowser(CreateVirtualRouterTestCase.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- closebrowser -->
  <system-out/>
  <testcase classname="lightstorm.polarin.testCases.CreateVirtualRouterTestCase" name="verify_that_user_should_be_able_to_create_new_Virtual_Router_at_the_Services" time="4.805"/>
  <system-out/>
  <testcase classname="lightstorm.polarin.testCases.CreateVirtualRouterTestCase" name="verify_that_user_should_navigate_to_Checkout_page_once_Virtual_Router_details_are_entered_and_click_on_Save" time="5.587"/>
  <system-out/>
  <testcase classname="lightstorm.polarin.testCases.CreateVirtualRouterTestCase" name="verify_that_Virtual_Router_details_along_with_Total_cost_should_be_displayed_in_the_Checkout_page_of_Virtual_Router_create_flow" time="8.716"/>
  <system-out/>
</testsuite> <!-- lightstorm.polarin.testCases.CreateVirtualRouterTestCase -->
